version: '3'

services:
  db:
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_DB=MyDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks: 
        - mynetwork

  api:
        image: imagem
        ports:
          - 5000:5000
        build: .
        links:
          - db
        depends_on:
          - "db"
        networks:
          - mynetwork
     
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local

networks:
  mynetwork:
     driver: bridge